language: ruby
rvm:
  - 1.9.2
env:
  - DB=mysql GOVUK_APP_DOMAIN=test.gov.uk RUBYOPT="-rpsych"
services:
  - elasticsearch
script:
  - bundle exec rake
bundler_args: --without=development
branches:
  except:
    - release
notifications:
  email: false
