migrated:
# Contacts
- contact
# Publisher
- answer
- guide
- help_page
- licence
- local_transaction
- place
- transaction
- simple_smart_answer
# Specialist Publisher
- aaib_report
- asylum_support_decision
- business_finance_support_scheme
- cma_case
- countryside_stewardship_grant
- drug_safety_update
- employment_appeal_tribunal_decision
- international_development_fund
- medical_safety_alert
- raib_report
- service_standard_report
- tax_tribunal_decision
- utaac_decision
# Other
- task_list

indexable:
#- dfid_research_output
- employment_tribunal_decision
#- european_structural_investment_fund
- maib_report
#- vehicle_recalls_and_faults_alert
