migrated:
# Collections Publisher
- coronavirus_landing_page
- mainstream_browse_page
- specialist_sector # topic format is mapped to specialist_sector in Rummager.
# Contacts
- contact
# Content Publisher - formats not indexable when published by Whitehall
- government_response:
    publishing_app: content-publisher
- news_story:
    publishing_app: content-publisher
- press_release:
    publishing_app: content-publisher
- world_news_story:
    publishing_app: content-publisher
# Publisher
- answer
- guide
- help_page
- licence
- local_transaction
- place
- transaction
- simple_smart_answer
# Specialist Publisher
- aaib_report
- asylum_support_decision
- business_finance_support_scheme
- cma_case
- countryside_stewardship_grant
- drug_safety_update
- employment_appeal_tribunal_decision
- employment_tribunal_decision
- european_structural_investment_fund # use Rummager name as mapping occurs before validation check
- export_health_certificate
- international_development_fund
- flood_and_coastal_erosion_risk_management_research_report
- maib_report
- marine_notice
- medical_safety_alert
- protected_food_drink_name
- raib_report
- research_for_development_output
- residential_property_tribunal_decision
- service_standard_report
- statutory_instrument
- tax_tribunal_decision
- traffic_commissioner_regulatory_decision
- uk_market_conformity_assessment_body
- utaac_decision
# Other
- calendar
- finder # Specialist Publisher and Whitehall
- history
- hmrc_manual
- hmrc_manual_section
- manual
- manual_section
- minister # from Whitehall, should be `ministerial_role`
- ministerial_role
- person
- policy
- recommended-link # Search admin
- service_manual_guide
- service_manual_homepage
- service_manual_service_standard
- service_manual_topic
- step_by_step_nav
- taxon:
  - /brexit
  - /transition
  - /world/afghanistan
  - /world/albania
  - /world/algeria
  - /world/andorra
  - /world/angola
  - /world/anguilla
  - /world/antigua-and-barbuda
  - /world/argentina
  - /world/armenia
  - /world/aruba
  - /world/australia
  - /world/austria
  - /world/azerbaijan
  - /world/bahamas
  - /world/bahrain
  - /world/bangladesh
  - /world/barbados
  - /world/belarus
  - /world/belgium
  - /world/belize
  - /world/benin
  - /world/bermuda
  - /world/bhutan
  - /world/bolivia
  - /world/bonaire-st-eustatius-saba
  - /world/bosnia-and-herzegovina
  - /world/botswana
  - /world/brazil
  - /world/british-antarctic-territory
  - /world/british-virgin-islands
  - /world/brunei
  - /world/bulgaria
  - /world/burkina-faso
  - /world/burundi
  - /world/cambodia
  - /world/cameroon
  - /world/canada
  - /world/cape-verde
  - /world/cayman-islands
  - /world/central-african-republic
  - /world/chad
  - /world/chile
  - /world/china
  - /world/colombia
  - /world/comoros
  - /world/congo
  - /world/costa-rica
  - /world/cote-d-ivoire
  - /world/croatia
  - /world/cuba
  - /world/curacao
  - /world/cyprus
  - /world/czech-republic
  - /world/democratic-republic-of-the-congo
  - /world/denmark
  - /world/djibouti
  - /world/dominica
  - /world/dominican-republic
  - /world/ecuador
  - /world/egypt
  - /world/el-salvador
  - /world/equatorial-guinea
  - /world/eritrea
  - /world/estonia
  - /world/eswatini
  - /world/ethiopia
  - /world/falkland-islands
  - /world/fiji
  - /world/finland
  - /world/france
  - /world/french-guiana
  - /world/french-polynesia
  - /world/gabon
  - /world/georgia
  - /world/germany
  - /world/ghana
  - /world/gibraltar
  - /world/greece
  - /world/grenada
  - /world/guadeloupe
  - /world/guatemala
  - /world/guinea
  - /world/guinea-bissau
  - /world/guyana
  - /world/haiti
  - /world/holy-see
  - /world/honduras
  - /world/hong-kong
  - /world/hungary
  - /world/iceland
  - /world/india
  - /world/indonesia
  - /world/iran
  - /world/iraq
  - /world/ireland
  - /world/israel
  - /world/italy
  - /world/jamaica
  - /world/japan
  - /world/jordan
  - /world/kazakhstan
  - /world/kenya
  - /world/kiribati
  - /world/kosovo
  - /world/kuwait
  - /world/kyrgyzstan
  - /world/laos
  - /world/latvia
  - /world/lebanon
  - /world/lesotho
  - /world/liberia
  - /world/libya
  - /world/liechtenstein
  - /world/lithuania
  - /world/luxembourg
  - /world/macao
  - /world/madagascar
  - /world/malawi
  - /world/malaysia
  - /world/maldives
  - /world/mali
  - /world/malta
  - /world/marshall-islands
  - /world/martinique
  - /world/mauritania
  - /world/mauritius
  - /world/mayotte
  - /world/mexico
  - /world/micronesia
  - /world/moldova
  - /world/monaco
  - /world/mongolia
  - /world/montenegro
  - /world/montserrat
  - /world/morocco
  - /world/mozambique
  - /world/myanmar
  - /world/namibia
  - /world/nauru
  - /world/nepal
  - /world/netherlands
  - /world/new-caledonia
  - /world/new-zealand
  - /world/nicaragua
  - /world/niger
  - /world/nigeria
  - /world/north-korea
  - /world/north-macedonia
  - /world/norway
  - /world/oman
  - /world/pakistan
  - /world/palau
  - /world/panama
  - /world/papua-new-guinea
  - /world/paraguay
  - /world/peru
  - /world/philippines
  - /world/pitcairn-island
  - /world/poland
  - /world/portugal
  - /world/qatar
  - /world/reunion
  - /world/romania
  - /world/russia
  - /world/rwanda
  - /world/samoa
  - /world/san-marino
  - /world/sao-tome-and-principe
  - /world/saudi-arabia
  - /world/senegal
  - /world/serbia
  - /world/seychelles
  - /world/sierra-leone
  - /world/singapore
  - /world/slovakia
  - /world/slovenia
  - /world/solomon-islands
  - /world/somalia
  - /world/south-africa
  - /world/south-georgia-and-south-sandwich-islands
  - /world/south-korea
  - /world/south-sudan
  - /world/spain
  - /world/sri-lanka
  - /world/st-helena-ascension-and-tristan-da-cunha
  - /world/st-kitts-and-nevis
  - /world/st-lucia
  - /world/st-maarten
  - /world/st-martin
  - /world/st-pierre-and-miquelon
  - /world/st-vincent-and-the-grenadines
  - /world/sudan
  - /world/suriname
  - /world/sweden
  - /world/switzerland
  - /world/syria
  - /world/taiwan
  - /world/tajikistan
  - /world/tanzania
  - /world/thailand
  - /world/the-gambia
  - /world/the-occupied-palestinian-territories
  - /world/timor-leste
  - /world/togo
  - /world/tonga
  - /world/trinidad-and-tobago
  - /world/tunisia
  - /world/turkey
  - /world/turkmenistan
  - /world/turks-and-caicos-islands
  - /world/tuvalu
  - /world/uganda
  - /world/ukraine
  - /world/united-arab-emirates
  - /world/uruguay
  - /world/usa
  - /world/uzbekistan
  - /world/vanuatu
  - /world/venezuela
  - /world/vietnam
  - /world/wallis-and-futuna
  - /world/western-sahara
  - /world/yemen
  - /world/zambia
  - /world/zimbabwe
- travel_advice
- travel_advice_index
- special_route:
  - '/help'
  - '/help/cookies'
  - '/find-local-council'

indexable: []

non_indexable_path:
- '/help/cookie-details'
- '/world/burma/news'

non_indexable:
- calculator
- license_finder
- smart_answer # this is the format for the `/<path>/y` flow landing page for smart answers
- special_route:
  - '/homepage'
  - '/tour'
  - '/help/ab-testing'
  - '/help.json'
  - '/uk-nationals-living-eu'
  - '/random'
  # from whitehall
  - "/BingSiteAuth.xml"
  - "/api"
  - "/apple-touch-icon-114x114.png"
  - "/apple-touch-icon-144x144.png"
  - "/apple-touch-icon-57x57.png"
  - "/apple-touch-icon-72x72.png"
  - "/apple-touch-icon-precomposed.png"
  - "/apple-touch-icon.png"
  - "/contact"
  - "/courts-tribunals"
  - "/email-signup"
  - "/email-signup/confirm"
  - "/email/subscriptions"
  - "/email/unsubscribe"
  - "/favicon.ico"
  - "/google6db9c061ce178960.html"
  - "/google991dec8b62e37cfb.html"
  - "/googlef35857dca8b812e7.html"
  - "/government"
  - "/government/get-involved"
  - "/government/how-government-works"
  - "/humans.txt"
  - "/info"
  - "/lloyds-share-offer-further-details"
  - "/lloydsfactsheet"
  - "/performance"
  - "/performance/big-screen"
  - "/robots.txt"
  - "/search.json"
  - "/search/opensearch.xml"
  - "/sitemap.xml"
  - "/sitemaps"
  - "/tour"
  - "/ukwelcomes"

# detailed formats
- detailed_guide
# whitehall formats
- about
- about_our_services
- accessible_documents_policy
- access_and_opening
- authored_article
- case_study
- complaints_procedure
- consultation
#- contact # migrated
- corporate_report
- correspondence
- decision
- document_collection
- equality_and_diversity
- facet
- facet_group
- facet_value
- facet_values
- fatality_notice
- field_of_operation
#- finder # migrated
- foi_release
- form
- government_response: # indexable when published by Content Publisher
    publishing_app: whitehall
- guidance
- html_publication
- impact_assessment
- imported
- independent_report
- international_treaty
- map
- media_enquiries
- membership
- national_statistics
- national_statistics_announcement
- news_story: # indexable when published by Content Publisher
    publishing_app: whitehall
- notice
- official_statistics
- official_statistics_announcement
- oral_statement
- organisation
- our_energy_use
- our_governance
- personal_information_charter
- petitions_and_campaigns
- policy_area
- policy_paper
- press_release: # indexable when published by Content Publisher
    publishing_app: whitehall
- procurement
- promotional
- publication
- publication_scheme
- recruitment
- regulation
- research
- services_and_information
- social_media_use
- speech
- staff_update
- standard
- statistical_data_set
- statistics
- statutory_guidance
- take_part
- terms_of_reference
- topical_event
- topical_event_about_page
- transparency
- welsh_language_scheme
- working_group
- world_location
- world_news_story: # indexable when published by Content Publisher
    publishing_app: whitehall
- worldwide_organisation
- written_statement
