migrated:
- answer
- contact
- guide
- help_page
- licence
- local_transaction
- place
- task_list
- transaction
- simple_smart_answer

indexable:
- aaib_report
#- asylum_support_decision
#- business_finance_support_scheme
#- cma_case
#- countryside_stewardship_grant
#- dfid_research_output
#- drug_safety_update
#- employment_appeal_tribunal_decision
#- employment_tribunal_decision
#- european_structural_investment_fund
#- international_development_fund
#- maib_report
#- medical_safety_alert
#- raib_report
#- service_standard_report
#- tax_tribunal_decision
#- utaac_decision
#- vehicle_recalls_and_faults_alert
