migrated:
# Contacts
- contact
# Publisher
- answer
- guide
- help_page
- licence
- local_transaction
- place
- transaction
- simple_smart_answer
# Specialist Publisher
- aaib_report
# Other
- task_list

indexable:
- asylum_support_decision
- business_finance_support_scheme
- countryside_stewardship_grant
- employment_appeal_tribunal_decision
- international_development_fund
- medical_safety_alert
- raib_report
- service_standard_report
- utaac_decision
#- cma_case
#- dfid_research_output
#- drug_safety_update
#- employment_tribunal_decision
#- european_structural_investment_fund
#- maib_report
#- tax_tribunal_decision
#- vehicle_recalls_and_faults_alert
