type: stemmer_override
rules: [
  "accessibility => accessib",  # not access
  "accessible => accessib",  # not access
  "animal => animal",  # not animation
  "animals => animal",  # not animation
  "animation => animat",  # not animal
  "animator => animat",  # not animal
  "appointeeship => appointe",  # match appointee
  "appropriation => appropriation", # not appropriate
  "appropriating => appropriation", # not appropriate
  "collection => collection",  # DfE COLLECT not collection
  "collections => collection",  # DfE COLLECT not collection
  "community => community",
  "complaint => complain",  # same as complain
  "complaints => complain",
  "corporate => corporate",  # not corporation
  "corporation => corporation",  # not corporal
  "directive => directive",
  "directives => directive",
  "equalities => equality",
  "equality => equality",
  "fertiliser => fertiliser",  # not fertilisation
  "fertilisers => fertiliser",  # not fertilisation
  "fiancee => fianc",  # also match fiance
  "fiancé => fianc",  # also match fiance
  "fiancée => fianc",  # also match fiance
  "governance => governance",  # not government
  "housing => housing",
  "intern => intern",
  "interns => intern",
  "internal => internal",
  "international => international",
  "mariner => mariner",  # not marine
  "nationality => nationality",  # not national
  "nationalities => nationality",
  "naturalization => naturalis",  # not natural, nature
  "parking => parking",  # not park
  "paye => paye",  # not pay
  "permitted => permitted",
  "practical => practical",
  "practice => practice",
  "probate => probate",  # not probation
  "publication => publication",
  "publications => publication",
  "recovery => recov",  # same as recover
  "recoverable => recov",  # same as recover
  "responsibility => responsib",  # not response, responsive
  "responsibilities => responsib",
  "responsible => responsib",
  "saving => saving",
  "savings => savings",
  "signing => signing",
  "sponsorship => sponsor",
  "tramway => tram",
  "tramways => tram",
  "universal => universal"
]
