---
base_path: "/search/guidance-and-regulation/email-signup"
content_id: 30974a3c-b86d-4f12-883d-783e97055690
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Guidance and regulation
description: You'll get an email when guidance and regulation is published.
details:
  email_filter_by:
  subscription_list_title_prefix: 'Guidance and regulation'
  filter:
    content_purpose_supergroup: guidance_and_regulation
  email_filter_facets:
  - facet_id: organisations
    facet_name: organisations
  - facet_id: world_locations
    facet_name: world locations
  - facet_id: topic
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_one_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_two_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
routes:
- path: "/search/guidance-and-regulation/email-signup"
  type: exact
