---
base_path: "/search/news-and-communications/email-signup"
content_id: 54fa4dca-4dfb-40a5-b860-127716f02e75
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: News and communications
description: You'll get an email each time news or communications are published.
details:
  filter:
    content_purpose_subgroup:
    - news
    - speeches_and_statements
  email_filter_by:
  email_filter_name:
  subscription_list_title_prefix: 'News and communications ' # whitespace intended
  email_filter_facets:
  - facet_id: people
    facet_name: people
  - facet_id: organisations
    facet_name: organisations
  - facet_id: world_locations
    facet_name: world locations
  - facet_id: topic
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_one_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_two_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: related_to_brexit
    filter_key: all_part_of_taxonomy_tree
    filter_value: d6c2de5d-ef90-45d1-82d4-5f2438369eea
    facet_name: topics
routes:
- path: "/search/news-and-communications/email-signup"
  type: exact
